version: '3.9'
services:
  caddy:
    image: caddy:2.8.4-alpine
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    environment:
      - ACME_AGREE=true
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy-data:/data
      - caddy-config:/config
    networks:
      - web

  nginx:
    image: nginx:1.27-alpine
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./www:/var/www/html:ro
      - ./certs:/etc/ssl:ro
    networks:
      - web

  traefik:
    image: traefik:v3.1
    command:
      - --providers.file.filename=/etc/traefik/traefik.yml
      - --api.dashboard=true
    ports:
      - '80:80'
      - '443:443'
      - '8080:8080'
    volumes:
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - web

networks:
  web:
    external: false

volumes:
  caddy-data: {}
  caddy-config: {}
  letsencrypt: {}

